# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Passgen < Formula
  desc "A secure and deterministic password generator"
  homepage "https://github.com/zapsaang/pass-gen"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zapsaang/pass-gen/releases/download/v0.1.0/pass-gen_Darwin_x86_64.tar.gz"
      sha256 "a75446fc6b1ec88f97d74ff022b4ea2b4a2caef91b694f631f991b60ad4326ea"

      def install
        bin.install "passgen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zapsaang/pass-gen/releases/download/v0.1.0/pass-gen_Darwin_arm64.tar.gz"
      sha256 "b8fb375ce4afca138670dfbaa8ce1d8f1d3b2b111f9a3764c98abedd4c540be3"

      def install
        bin.install "passgen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zapsaang/pass-gen/releases/download/v0.1.0/pass-gen_Linux_x86_64.tar.gz"
      sha256 "22d9519cbc89d580044ebcc38fb6445d14149581fa92a97fd2107e1eda9c8048"
      def install
        bin.install "passgen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zapsaang/pass-gen/releases/download/v0.1.0/pass-gen_Linux_arm64.tar.gz"
      sha256 "1d3b472b62cdb496ecd59f091234b83870eaae0f43e0cbc0cbf3e8584973fdd0"
      def install
        bin.install "passgen"
      end
    end
  end

  test do
    system "#{bin}/passgen --version"
  end
end
