# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Passgen < Formula
  desc "A secure and deterministic password generator"
  homepage "https://github.com/zapsaang/pass-gen"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zapsaang/pass-gen/releases/download/v0.1.0/pass-gen_Darwin_x86_64.tar.gz"
      sha256 "d6482593c58daaa68b93ab09535dda4116707c9d9055da7dd0982ddb663c47de"

      def install
        bin.install "passgen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zapsaang/pass-gen/releases/download/v0.1.0/pass-gen_Darwin_arm64.tar.gz"
      sha256 "c0fa2eb5b10e755cbe3aaab55c396a5c531bc7ac2104a0ffb553da73fba89a83"

      def install
        bin.install "passgen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/zapsaang/pass-gen/releases/download/v0.1.0/pass-gen_Linux_x86_64.tar.gz"
      sha256 "4966f0a0e3638cca5b04b23a6c282c26410ab1c908afb153614764393d1d5229"
      def install
        bin.install "passgen"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zapsaang/pass-gen/releases/download/v0.1.0/pass-gen_Linux_arm64.tar.gz"
      sha256 "2139049524332d5c68c0ad9f90150c14abf3de2293bb14befbf0ccf7cff5ea4d"
      def install
        bin.install "passgen"
      end
    end
  end

  test do
    system "#{bin}/passgen --version"
  end
end
